##management:
##  endpoints:
##    web:
##      exposure:
##        include: "*"
##      base-path:
##    enabled-by-default: true
#
#info:
#  app:
#    name: "Spring Boot"
#    id: "10086"
#    version: "v1.0.0"
#
#management:
#  security:
#    enabled: false
#endpoints:
#  shutdown:
#    enabled: true
#  enabled: false
#  health.enabled: true
#
##  beans:
##    id: "mybeans"
##    enabled: false
#
